series: GLFW Graphics
title: Gaussian Blur Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This demo demonstrates the implementation of Gaussian blur filter using fragment shader.
language: C++
tags:
  - Graphics
extra_resources:
  - title: OpenGL 4 Shading Language Cookbook (2nd ed.), by David Wolff
    link: "https://www.packtpub.com/game-development/opengl-4-shading-language-cookbook-second-edition"
connections:
  - series: GLFW Graphics
    title: Basic Particle Emitter
